---
title: "Titanic"
output:
  pdf_document: default
  html_document:
    df_print: paged
date: "2025-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(tidyr)
library(ggplot2)
library(mice)
library(fastDummies)
library(car)
library(ResourceSelection)
library(randomForest)
library(caret)
library(cvms)
library(gridExtra)
```
# Carregamento e Pré-processamento dos Dados
```{r, results='hide'}
# Carregamento dos dados
data_train = read.csv('train.csv')
data_test = read.csv('test.csv')
gen_sub = read.csv('gender_submission.csv')
head(data_train)
```
```{r}
head(data_test)
```
```{r}
head(gen_sub)
```

```{r, results = 'hide'}
# Remoção de variáveis irrelevantes
data_train = subset(data_train, select = -c(Name, Ticket, Cabin))
data_test = subset(data_test, select = -c(Name, Ticket, Cabin))
```

# Tratamento de Valores Ausentes

```{r}
# Combinação dos datasets
data_test$Survived = gen_sub$Survived
data = rbind.fill(data_train, data_test)

# Identificação de valores irregulares e torná-los NA
data[data == ''] = NA

summary(is.na(data)) # 263 NAs em Age / 1 NA em Fare / 2 NA em Embarked
```

```{r}
# Imputação de Embarked (Moda)
data$Embarked = replace_na(data$Embarked, 'S')

# Imputação de Age (Mediana)
data$Age = replace_na(data$Age, median(data$Age, na.rm = T))

# Criação de variáveis dummy
data = dummy_cols(
  data, 
  select_columns = c('Sex', 'Pclass', 'Embarked'),
  remove_first_dummy = TRUE,
  remove_selected_columns = TRUE
)

# Imputação final com MICE para Fare
data_aux = data[,-c(1,2)]
set.seed(28051996)  
imp = mice(data_aux)
data_aux = complete(imp, 1)

# Reconstrução do dataset final
data = cbind(data[,c(1,2)], data_aux)
data_train = data[1:891,-1]
data_test = data[892:1309,]

```

# Modelagem com Random Forest
```{r, results = 'hide'}
# Modelo inicial
set.seed(28051996)
model = randomForest(factor(Survived) ~ ., data = data_train, proximity = T)

# Validação cruzada
train_control = trainControl(
  method = 'cv',
  number = 10,
  search = 'random',
  classProbs = TRUE,
  summaryFunction = twoClassSummary
)

# Função customizada de métricas
customSummary = function(data, lev = NULL, model = NULL) {
  out = twoClassSummary(data, lev, model)
  tp = sum(data$obs == lev[2] & data$pred == lev[2])
  fp = sum(data$obs == lev[1] & data$pred == lev[2])
  out = c(out, Precision = tp/(tp+fp))
  return(out)
}

train_control$summaryFunction = customSummary

# Ajuste dos rótulos para validação cruzada
data_train_aux = data_train
data_train_aux$Survived <- factor(
  data_train_aux$Survived,
  levels = c(0, 1),
  labels = c("No", "Yes")
)

# Tuning do parâmetro mtry
tuneGrid = expand.grid(mtry = seq(1,10,1))
set.seed(28051996)
cv_model_train = train(
  factor(Survived) ~ .,
  data = data_train_aux,
  trControl = train_control,
  method = 'rf',
  metric = 'ROC',
  tuneGrid = tuneGrid
)

# Modelo final otimizado
cv_best_model = train(
  factor(Survived) ~ .,
  data = data_train_aux,
  trControl = train_control,
  method = 'rf',
  metric = 'ROC',
  tuneGrid = data.frame(mtry = 3)
)
```
# Avaliação do Modelo

```{r}
# Matrizes de confusão
y_hat_train = predict(model, data_train)
cm_train = confusionMatrix(y_hat_train, factor(data_train$Survived), mode = 'everything')
cm_train_df = as.data.frame(cm_train$table)
names(cm_train_df) <- c("Prediction", "Reference", "N")

y_hat_best_train = factor(ifelse(predict(cv_best_model, data_train) == 'No', 0, 1))
cm_best_train = confusionMatrix(y_hat_best_train, factor(data_train$Survived), mode = 'everything')
cm_best_train_df = as.data.frame(cm_best_train$table)
names(cm_best_train_df) <- c("Prediction", "Reference", "N")

# Visualização comparativa
plt1 = plot_confusion_matrix(cm_train_df,
                             target_col = "Reference",
                             prediction_col = "Prediction",
                             palette = "Blues",
                             place_x_axis_above = F, 
                             add_normalized = FALSE,
                             rotate_y_text = F,
                             add_col_percentages = FALSE,
                             add_row_percentages = FALSE,
                             add_arrows = FALSE) + 
                             ggtitle('Parâmetros Padrão')

plt2 = plot_confusion_matrix(cm_best_train_df, 
                             target_col = "Reference",
                             prediction_col = "Prediction",
                             palette = "Blues",
                             place_x_axis_above = F, 
                             add_normalized = FALSE,
                             rotate_y_text = F,
                             add_col_percentages = FALSE,
                             add_row_percentages = FALSE,
                             add_arrows = FALSE) + 
                             ggtitle('Melhores Parâmetros')

grid.arrange(plt1, plt2, ncol=2)

# Importância das variáveis
imp_model = importance(cv_best_model$finalModel)
ggplot(data = data.frame(Variable = rownames(imp_model), Importance = imp_model[,1]),
       aes(x = reorder(Variable, Importance), y = Importance)) +
       geom_col(fill = 'steelblue') +
       coord_flip() +
       ggtitle('Importância das Variáveis')
```

# Previsões no Conjunto de Teste

```{r}
y_hat_best_test = factor(ifelse(predict(cv_best_model, data_test) == 'No', 0, 1))
cm_best_test = confusionMatrix(y_hat_best_test, factor(gen_sub$Survived), mode = 'everything')
cm_best_test_df = as.data.frame(cm_best_test$table)
names(cm_best_test_df) <- c("Prediction", "Reference", "N")

plot_confusion_matrix(cm_best_test_df,
                      target_col = "Reference",
                      prediction_col = "Prediction",
                      palette = "Blues",
                      place_x_axis_above = F, 
                      add_normalized = FALSE,
                      rotate_y_text = F,
                      add_col_percentages = FALSE,
                      add_row_percentages = FALSE,
                      add_arrows = FALSE) + 
                      ggtitle('Desempenho no Conjunto de Teste')
```